### ISSUE TITLE
ELF GoLang Emulation Failure

### ISSUE THREAD

**Issue by ddash-ct** [dod-cyber-crime-center/rugosa#10]
GobRAT samples (https://blogs.jpcert.or.jp/en/2023/05/gobrat.html) are x64 ELF binaries programmed in GoLang (example SHA256 hash ca6591e246e581af1411735df514a347c43d6d32663d2584420cbbee8c2388b9).

Rugosa does not currently support acquiring a context within the binary. e.g. `context = emulator.context_at(0x619A16)` results in a `NoneType` result.

The emulator appears to (correctly) select the `x86_64ProcessorContext` as the `_context_class`, and the following debug messages are obtained:
```
[*] Emulating call level 0 for function at 0x00619A16: follow_loops = False, exhaustive = True
[*] Iterating contexts for call level: 0
```

Request supporting the x86/x64 instruction set for these binaries.

**Comment by dc3-tsd** [comment]
Thanks for letting us know about this.  We verified the issue and are currently working on a fix for it that will be in our next release.
