### ISSUE TITLE
Function Arguments Bug

### ISSUE THREAD

**Issue by ddash-ct** [dod-cyber-crime-center/rugosa#3]
Encountering a bug when pulling function arguments for 64-bit sample `f70def4172a06ee201adc7500d464973` at 0x18000426C. The function signature for the function at 0x180003E88 referenced at 0x18000426C is `_BYTE *__fastcall sub_180003E88(_BYTE *a1, int a2, char a3);`. 

While the second argument is type `int`, it should be interpreted as a 64-bit integer since the sample is 64-bit. Since the value in `rdx` is 0x180020350, this is being cut as a 32-bit integer 0x80020350 when pulling function arguments.

**Comment by dc3-tsd** [comment]
After looking at the sample, it looks like IDA is producing the wrong information. It should have typed the argument as "int64", "longlong", or "qword".  Dragodis (and in turn rugosa) are simply exposing this incorrect information from IDA.

What you can do is use Dragodis to manually fix the function signature before emulating.

```python
sig = dis.get_function_signature(0x180003e88)
sig.parameters[1].data_type = "int64"
```
