### ISSUE TITLE
Support Vector Packed Bitwise instructions

### ISSUE THREAD

**Issue by ddash-ct** [dod-cyber-crime-center/rugosa#7]
Malware such as [Meduza](https://russianpanda.com/2023/06/28/Meduza-Stealer-or-The-Return-of-The-Infamous-Aurora-Stealer/) leverage Vector Packed Bitwise instructions including `vpxor`, `vmovdqa`, `vmovaps`, and others for inline string decryption. 

An example in Meduza Stealer sample `9022192413dda223b6e8afd73a22cfaa`  can be found in code starting at 0x419988.

Requesting addition of support for these instructions.

**Comment by dc3-tsd** [comment]
This support has been added in the most recent release.  Please let us know if this works for you.

**Comment by ddash-ct** [comment]
This is great, thank you!
